import type { Href } from "expo-router";

/**
 * Expo Router href-ууд — бүлэг тодорхойлсон замууд нэг ижил замын нэрийг
 * үйлчлүүлэгч / үзүүлэгч хоёр дээр давхардуулахгүй.
 */
export const routes = {
  splash: "/splash",
  login: "/login",
  register: "/register",
  intro: "/intro",
  customerHome: "/(customer)/home",
  customerNotifications: "/(customer)/notifications",
  customerNotificationSettings: "/(customer)/notification-settings",
  customerSearch: "/(customer)/search",
  customerWallet: "/(customer)/wallet",
  customerPaymentMethods: "/(customer)/payment-methods",
  customerPaymentMethodsAddCard: "/(customer)/payment-methods/add-card",
  customerClinics: "/(customer)/clinics",
  customerDoctors: "/(customer)/doctors",
  customerMyOrders: "/(customer)/my-orders",
  customerFreeConsult: "/(customer)/free-consult",
  customerFreeConsultBook: "/(customer)/free-consult/book",
  customerAdvice: "/(customer)/advice/index",
  customerAppointments: "/(customer)/appointments",
  customerInsurance: "/(customer)/insurance",
  customerChat: "/(customer)/chat",
  customerChatDetail: "/(customer)/chat-detail",
  providerDashboard: "/(provider)/dashboard",
  providerNotifications: "/(provider)/provider-notifications",
  providerNotificationSettings: "/(provider)/notification-settings",
  providerDoctors: "/(provider)/doctors",
  providerDoctorRegister: "/(provider)/doctor-register",
  providerProfile: "/(provider)/provider-profile",
  providerClinicProfile: "/(provider)/clinic-profile",
  providerClinicRegister: "/(provider)/clinic-register",
  providerOrdersToday: "/(provider)/orders/today",
  providerOrdersRequests: "/(provider)/orders/requests",
  providerSchedule: "/(provider)/schedule",
  providerScheduleAddSlot: "/(provider)/schedule/add-slot",
  providerServices: "/(provider)/services",
  providerServicesNew: "/(provider)/services/new",
  providerRevenue: "/(provider)/revenue",
  providerBookings: "/(provider)/bookings",
  providerChat: "/(provider)/chat",
  providerChatDetail: "/(provider)/chat-detail",
  systemAdminDashboard: "/(system-admin)/admin-dashboard",
  adminRegistrations: "/(system-admin)/admin-registrations",
  adminProviders: "/(system-admin)/admin-providers",
  adminUsers: "/(system-admin)/admin-users",
  adminModeration: "/(system-admin)/admin-moderation",
  adminNotifications: "/(system-admin)/admin-notifications",
  adminProfile: "/(system-admin)/admin-profile",
  providerPending: "/provider-pending",
} as const satisfies Record<string, Href>;
